// lang.js — Hindi / English translations for KaalBhairav.org

const translations = {
  en: {
    // ABOUT PAGE
    about_header: 'About Kaal Bhairav',
    about_sub: 'Iconography, significance, and his place across the great traditions of Shaivism',
    about_ico_title: 'Iconography — The Form of Bhairav',
    about_ico_intro: 'Kaal Bhairav\'s form is deliberately designed to be overwhelming to the senses — to confront the ego directly. He is described across texts as:',
    about_weapons_title: 'The 8 Weapons (Ashtayudha)',
    about_name_title: 'The Meaning of the Name',
    about_card_kaal_title: 'Kaal (काल)',
    about_card_kaal_text: 'Means both "Time" and "Death." Bhairav as Kaal is Time personified — the force that dissolves all things. He is simultaneously the destroyer and the one who transcends destruction. He is called "Mahakal" — beyond all time.',
    about_card_bhairav_title: 'Bhairav (भैरव)',
    about_card_bhairav_text: 'Derived from the root "Bhiru" (fear) or "Bha-Ra-Va" — the three syllables symbolizing: Bha = Bharana (sustaining), Ra = Ramana (dissolving), Va = Vamana (creating). Bhairav is thus a complete cosmic force.',
    about_card_kshtra_title: 'Kshetrapala',
    about_card_kshtra_text: 'Protector of the field (kshetra) — both the field of the body and the sacred field (temple, cremation ground). He is the guardian of thresholds and boundaries between worlds.',
    about_card_danda_title: 'Dandapani',
    about_card_danda_text: 'Holder of the staff (danda) of justice. As Kotwal, he administers divine law. His danda cannot be escaped by any soul — every action is recorded and every karma is addressed.',
    about_shaiva_tag: 'Shaiva Siddhanta &amp; Shaiva Agamas',
    about_shaiva_title: 'In Shaiva Tradition',
    about_shaiva_text: 'In the classical Shaiva tradition, Bhairav is understood as one of Shiva\'s most important manifestations. The Shaiva Agamas — 64 primary texts — include the <em>Bhairavagama</em> which is dedicated entirely to Bhairav worship. Bhairav is considered the "krodha-murti" (form of righteous wrath) of Shiva — the aspect that punishes transgression and protects dharma.',
    about_kashmir_tag: 'Kashmir Shaivism (Trika)',
    about_kashmir_title: 'In Kashmir Shaivism',
    about_kashmir_text: 'In the non-dual Kashmir Shaivism of Abhinavagupta and Utpaladeva, Bhairav is the highest symbol of pure consciousness itself — <em>Paramashiva</em>. The Trika tradition centers on three goddesses (Para, Parapara, Apara) with Bhairav as their lord. Abhinavagupta\'s <em>Tantraloka</em> describes Bhairav as the universal consciousness that experiences itself through the play of manifestation and dissolution. His fierce form is understood as pure delight (<em>ananda</em>) — not wrath.',
    about_nath_tag: 'Nath Sampradaya',
    about_nath_title: 'In the Nath Tradition',
    about_nath_text: 'Gorakshnath and the Nath lineage revere Bhairav as the archetypal Siddha — the perfected yogi who has mastered the body, mind, and death itself. The Naths practice Bhairav sadhana as a path to Kaya-siddhi (bodily perfection) and Kaala-vijaya (conquest of time/death). Bhairav appears in many Nath texts as the teacher of Gorakshnath himself.',
    about_shakta_tag: 'Shakta Tradition',
    about_shakta_title: 'Bhairav and the Shaktas',
    about_shakta_text: 'In the Shakta tradition, Bhairav is inseparable from his Shakti. The 64 Yoginis — powerful tantric goddesses — each have a corresponding Bhairav. The 64 Bhairava-Yogini pairs govern the entire Tantric cosmos. In the Devi Bhagavata and Lalita Sahasranama tradition, Bhairav appears as Kaal Bhairav who guards the outer precincts of the Devi\'s sacred realm.',
    about_traditions_title: 'Bhairav Across Traditions',
    about_deeper_title: 'The Deeper Teaching',
    about_deeper_text: 'Kaal Bhairav is not merely a deity to be propitiated — he is a mirror. When you stand before him, you see what you truly are: consciousness wearing a temporary body, moving through time, destined to dissolve back into the infinite. The skulls he wears are every ego that has come before you.<br><br>His gift is not wealth or power — it is <em>fearlessness</em>. To know Bhairav is to know that nothing can truly harm the Self. Time destroys all forms — but you are not a form. You are the one who witnesses forms arising and dissolving.<br><br><em class="text-gold">This is the supreme teaching of Kaal Bhairav.</em>',

    // STORIES PAGE
    stories_header: 'Sacred Stories',
    stories_sub: 'Legends from Shiva Purana, Skanda Purana, Linga Purana &amp; Tantric Texts',
    story1_src: 'Source: Shiva Purana — Shatarudra Samhita; Skanda Purana — Kashi Khanda',
    story1_title: 'The Birth of Kaal Bhairav — The Beheading of Brahma',
    story1_body: 'In the primordial age, a great argument erupted between Lord Brahma (the Creator) and Lord Vishnu (the Preserver) over who was supreme. Both claimed to be the ultimate reality. At that moment, a blazing pillar of fire — infinite, without beginning or end — manifested between them. This was Lord Shiva as the <em>Jyotirlinga</em>, the cosmic light-pillar.<br><br>Brahma and Vishnu agreed: whoever finds the end of this pillar is supreme. Vishnu took the form of Varaha (boar) and dug downward. Brahma took the form of a swan and flew upward. Vishnu searched for thousands of years and could not find the bottom. Humbled, he returned and accepted Shiva\'s supremacy.<br><br>Brahma, however, was overtaken by his five heads\' combined ego. On his way upward, he passed a <em>ketaki</em> flower drifting down. He asked the flower where it came from. The flower said it had been drifting for thousands of years from the top of the pillar. Brahma, desperate, made an agreement with the flower to lie for him — to claim that Brahma had reached the top.<br><br>When Brahma returned and falsely proclaimed his victory before Shiva, Shiva — who is <em>omniscient</em> — was filled with cosmic fury at this <em>brahmanicide of truth</em>. His anger took form as a being of terrifying aspect: <strong class="text-gold">Kaal Bhairav</strong>.<br><br>Kaal Bhairav manifested from Shiva\'s third eye (or from his left eyebrow, in some versions) — dark as a storm cloud, with blazing eyes, wearing a garland of skulls, holding the trident and a kapala (skull bowl). In one swift motion, he severed Brahma\'s fifth head — the one that had spoken the lie, the one representing false ego and pride. Brahma was left with four heads, humbled before Shiva.<br><br>But even as a manifestation of Shiva, Bhairav had committed <em>brahmahatya</em> — the sin of harming a Brahmin (Brahma is the ultimate Brahmin). The severed skull of Brahma stuck to Bhairav\'s hand and could not be removed. This is why Bhairav carries the <em>kapala</em> — the skull bowl. He became a wandering ascetic, a Kapalika, bearing the mark of his deed.<br><br>He wandered across all the sacred tirthas of the universe, carrying the skull. Wherever he went, the skull clung to him. Finally, he arrived at <strong class="text-gold">Kashi (Varanasi)</strong>. The moment his foot touched Kashi\'s soil, the skull fell from his hand. The great sin of brahmahatya was absolved. This is why Kashi is considered the ultimate liberator of all sins — even the sin of Kaal Bhairav was washed away here.<br><br>Moved by the holiness of Kashi, and on the request of Lord Shiva, Bhairav remained in Kashi forever as its <em>Kotwal</em> — the divine guardian and administrator of the eternal city.',
    story2_src: 'Source: Skanda Purana — Kashi Khanda, Chapter 31',
    story2_title: 'Bhairav Becomes Kotwal of Kashi',
    story2_body: 'After being absolved of his sin at Kashi, Kaal Bhairav stood before Lord Shiva in the form of the great lingam at Vishwanath. Shiva, pleased with Bhairav\'s penance and his act of righteousness in punishing Brahma\'s ego, declared:<br><br><em style="border-left:2px solid var(--gold); padding-left:1rem; display:block; color:var(--gold-pale);">"You shall be the eternal Kotwal of this city. No soul shall enter or depart Kashi without your knowledge. You shall be my representative here. Those who worship you with devotion shall be freed from all fears and the cycle of rebirth."</em><br><br>From that day, Kaal Bhairav took up his residence at Kashi. He roams the cremation ghats — particularly <strong class="text-gold">Manikarnika Ghat</strong> — with his dog. He is the one who whispers the <em>Tarak Mantra</em> into the ear of every dying person in Kashi, granting them instant liberation regardless of their past karma.<br><br>His <em>danda</em> (staff) is the symbol of his authority. He carries a staff of justice, a noose to bind the wicked, and the kapala to feed the departed souls. He is simultaneously <em>Dandapani</em> (bearer of the staff of punishment) and the most compassionate liberator for souls who surrender to him.',
    story3_src: 'Source: Linga Purana; Tantric tradition',
    story3_title: 'Kaal Bhairav and the Demon Durgama',
    story3_body: 'The demon Durgama performed severe austerities and obtained from Brahma the boon that no god, man, or creature could kill him — except a child (<em>bala</em>) or an old person (<em>vriddha</em>). With this boon, Durgama spread terror across the three worlds, driving the gods from their abodes and plunging the universe into chaos.<br><br>The gods approached Lord Shiva for help. Shiva manifested Bhairav in the form of <strong class="text-gold">Batuk Bhairav</strong> — a young boy, eternally 16 years old. This childlike form of Bhairav approached Durgama playfully, as if unaware of any threat. The demon laughed at the child and attacked — only to be slain by Batuk Bhairav\'s trident in an instant.<br><br>This story teaches that the most fearsome power can reside in the simplest, most unassuming form. Batuk Bhairav is worshipped for protection, especially of children and households, and his mantra is considered extraordinarily powerful for removing obstacles and enemies.',
    story4_src: 'Source: Uttara Kalamrita; Kashi Kotwal oral tradition',
    story4_title: 'The Sacred Dog — Bhairav\'s Vahana',
    story4_body: 'There is a story from Kashi\'s oral tradition about why the dog is Bhairav\'s vehicle. Once, Brahmin priests in Kashi grew arrogant about their caste status and refused to feed a starving dog near the temple. The dog, near death from hunger, cried out.<br><br>That night, Lord Shiva appeared in the dream of the head priest in his Bhairav form and said: <em>"That dog is my body. You have starved me. The dog who appears to be a stray — I reside within it. Those who feed my dog, feed me. Those who torment it, torment me."</em><br><br>From that time forward, it became a sacred practice in Kashi to feed dogs — especially black dogs — as an act of Bhairav seva. The tradition continues to this day. A <em>dog\'s yelp at night</em> is considered a sign of Bhairav\'s presence, a reminder that the divine walks the streets of Kashi in many forms.',
    story5_src: 'Source: Siddha Tantra tradition; Abhinavagupta\'s Tantraloka',
    story5_title: 'Bhairav and the Kapalika Tradition',
    story5_body: 'After the beheading of Brahma, Bhairav wandered as the first <em>Kapalika</em> ascetic — carrying the skull, bearing the mark of the ultimate sin, living outside all social norms. He ate from the skull, used cremation grounds as his home, wore skulls as ornaments.<br><br>The Kapalika tradition — one of the earliest Tantric sects — took Bhairav as their founding deity, modeling themselves on his wandering asceticism. They practiced in cremation grounds, used skull-bowls, and followed left-hand Tantric (<em>vamachara</em>) paths.<br><br>The deeper symbolism is profound: Bhairav carries the skull of Brahma to show that even <em>the greatest ego in creation</em> becomes an empty vessel — a mere bowl for Bhairav to feed from. The skull represents the dissolution of individual identity into cosmic consciousness. This is the core teaching of Kaal Bhairav: <em>ego is the only real sin, and time destroys all ego.</em>',
    btn_explore_64: 'Explore the 64 Forms of Bhairav →',
    btn_pooja_vidhi: 'Pooja Vidhi →',

    // 64 BHAIRAV PAGE
    bhairav64_header: 'The 64 Forms of Bhairav',
    bhairav64_sub: 'The Ashtabhairav and their manifestations — guardians of the 8 directions of the cosmos',
    bhairav64_intro_title: 'Understanding the 64 Bhairavas',
    bhairav64_list_title: 'Complete List — All 64 Bhairavas',
    bhairav64_list_sub: 'As enumerated in the Bhairavagama and Rudrayamala Tantra',
    bhairav64_8_title: 'The 8 Ashtabhairavas',
    bhairav64_sources_title: '📚 Textual Sources',
    bhairav64_intro_p1: 'According to the Shaiva Tantric tradition (particularly the <em>Bhairavagama</em> and <em>Rudrayamala Tantra</em>), there are <strong class="text-gold">64 Bhairavas</strong> organized into 8 primary forms called the <strong class="text-gold">Ashtabhairava</strong> (Eight Bhairavas). Each of these 8 primary Bhairavas commands 8 sub-forms — making 8 × 8 = 64. They collectively preside over the 8 directions of the cosmos, 8 cremation grounds (<em>ashta shmashana</em>), and 8 aspects of Tantric power (<em>ashta siddhi</em>).',
    bhairav64_intro_p2: 'In Kashi (Varanasi), the Ashtabhairav are stationed at 8 points around the city, forming a sacred protective ring — the <em>Kashi Ashtabhairav Chakra</em> — that guards the holy city. Completing a pilgrimage to all 8 Bhairav shrines in Kashi is considered deeply auspicious.',
    bhairav64_sources_text: 'The enumeration and descriptions of the 64 Bhairavas are found primarily in:',

    // KASHI PAGE
    kashi_header: 'Kaal Bhairav &amp; Kashi',
    kashi_page_sub: 'The eternal city and its cosmic guardian — an inseparable bond since the beginning of time',
    kashi_intro_title: 'Kashi — The City That Never Sleeps',
    kashi_kotwal_title: 'The Kotwal — Divine Police Commissioner',
    kashi_powers_title: 'Bhairav\'s Powers Within Kashi',
    kashi_temple_title: 'The Kaal Bhairav Temple — Varanasi',
    kashi_moksha_title: 'Why Kashi Grants Moksha',
    kashi_ashta_title: 'The Eight Bhairavas of Kashi',
    kashi_intro_p1: '<strong class="text-gold">Kashi (Varanasi)</strong> is not merely a city — it is a cosmic axis, a place where the boundaries between the living world and the realm beyond are permanently thin. According to the <em>Kashi Khanda</em> of the Skanda Purana, Kashi stands on the tip of Lord Shiva\'s trident — suspended between heaven and earth, never truly touching the ground.',
    kashi_intro_p2: 'In this sacred city, death itself becomes liberation (<em>moksha</em>). Every soul that departs from Kashi is said to receive the <strong class="text-gold">Tarak Mantra</strong> — the mantra of crossing — whispered directly into the ear by Lord Shiva. This is why Kashi has been the destination of pilgrims, ascetics, and the dying for thousands of years.',
    kashi_intro_p3: 'But Kashi requires a guardian — an eternal Kotwal — to maintain its cosmic order, protect its boundaries, and ensure that no soul departs without the grace of liberation. That guardian is <strong class="text-gold">Kaal Bhairav</strong>.',
    kashi_kotwal_src: 'Source: Kashi Khanda, Skanda Purana; Linga Purana',
    kashi_kotwal_story: 'How Kaal Bhairav Became the Kotwal of Kashi',
    kashi_kotwal_body: 'When Lord Shiva chose Kashi as his permanent abode, he needed to appoint a guardian who would govern the eternal city with absolute authority. The city needed a deity powerful enough to command respect from gods, demons, and humans alike — one who would maintain dharmic order and ensure that every soul reaching Kashi\'s borders received liberation.<br><br>Shiva appointed <strong class="text-gold">Kaal Bhairav</strong> as the <em>Kshetrapala</em> (protector of the field) and <em>Kotwal</em> (divine commissioner) of Kashi. The title "Kotwal" is significant — in ancient India, the Kotwal was the city\'s chief law enforcer, responsible for justice, order, and the registry of all citizens. Bhairav keeps the cosmic registry of every soul in Kashi.<br><br>The <em>Kashi Khanda</em> states: <em>"Without first taking the darshan of Kaal Bhairav, the Kotwal of Kashi, one\'s pilgrimage to Kashi Vishwanath is incomplete."</em> This is why, to this day, devotees visit the Kaal Bhairav temple before proceeding to the Kashi Vishwanath Jyotirlinga.',
    kashi_card1_title: 'Keeper of Cosmic Law',
    kashi_card1_text: 'Bhairav registers every soul that enters Kashi. No one can reside permanently in the city without his permission — this is the ancient tradition still observed by those settling in Varanasi.',
    kashi_card2_title: 'Lord of Liberation',
    kashi_card2_text: 'Within Kashi\'s boundaries, even Lord Yama (the god of death) has no authority. It is Bhairav alone who presides over death here, and he ensures that every departing soul receives moksha.',
    kashi_card3_title: 'Protector of the City',
    kashi_card3_text: 'Bhairav roams the streets of Kashi, especially at night, guarding against negative forces, malevolent spirits, and those who would disturb the city\'s sacred peace.',
    kashi_card4_title: 'Pilgrimage Gateway',
    kashi_card4_text: 'Ancient tradition holds that one must seek Bhairav\'s permission before undertaking any pilgrimage within Kashi. His darshan opens the door to the city\'s deeper spiritual blessings.',
    kashi_card5_title: 'Master of the Night',
    kashi_card5_text: 'Bhairav is most active from midnight to dawn in Kashi. The cremation grounds of Manikarnika and Harishchandra Ghat are his domain — places where he presides over the transition between life and death.',
    kashi_card6_title: 'Shiva\'s Representative',
    kashi_card6_text: 'Bhairav acts as Shiva\'s direct representative in Kashi. To honor Bhairav is to honor Shiva himself — the two are considered non-different within Kashi\'s sacred geography.',
    kashi_temple_p1: 'The <strong class="text-gold">Kaal Bhairav Mandir</strong> on Kaal Bhairav Gali in Varanasi is the most important Bhairav shrine in India. The deity here is worshipped as the sovereign ruler of Kashi — and the temple receives thousands of devotees daily.',
    kashi_temple_p2: 'One of the most distinctive features of this temple is the offering of <strong class="text-gold">Madhya (liquor)</strong> — the deity here is known to accept and consume alcohol as naivedya. This is a rare and ancient Tantric tradition — Bhairav as the lord of the cremation grounds accepts what society rejects.',
    kashi_temple_p3: 'The temple also keeps a sacred <strong class="text-gold">black dog</strong> — Bhairav\'s vahana — within the premises. Feeding and honoring this dog is considered a direct act of devotion to Bhairav himself.',
    kashi_moksha_src: 'Source: Kashi Khanda, Skanda Purana; Shiva Purana',
    kashi_moksha_story: 'The Tarak Mantra and Bhairav\'s Role',
    kashi_moksha_body: 'The <em>Kashi Khanda</em> describes a divine arrangement: every soul that dies within the boundaries of Kashi — the <em>Pancha Koshi</em> — is liberated. This liberation occurs through a specific mechanism. At the moment of death, Lord Shiva himself appears and whispers the <em>Tarak Mantra</em> into the dying person\'s ear.<br><br>But this sacred arrangement is maintained and protected by <strong class="text-gold">Kaal Bhairav</strong>. It is he who ensures no negative force disrupts this process, he who keeps the boundaries of Kashi sacred, and he who registers each departing soul and confirms their liberation. The Kotwal, in this sense, is the administrator of moksha itself.<br><br>This is why the tradition says: <em>"Kashi mein mara, toh mukti mili"</em> — "Die in Kashi and you are free." But behind this liberation stands Kaal Bhairav, the unseen guardian who makes the promise of Kashi real.',
    kashi_closing: 'Kashi and Bhairav are one. The city is his body — the Ganga its lifeblood, the ghats his steps, the cremation pyres his eyes. To walk in Kashi is to walk within Bhairav himself.<br><br>Every narrow gali, every lamp lit at dusk, every chant rising at Dashashwamedh — all of it reverberates with his presence. He sees every soul, knows every karma, and silently guides each one toward liberation.<br><br><em class="text-gold">Jay Kaal Bhairav. Jay Kashi Vishwanath.</em>',
    btn_read_stories: 'Read Sacred Stories →',

    // POOJA VIDHI PAGE
    pooja_header: 'Pooja Vidhi',
    pooja_sub: 'Complete worship procedure — performed with devotion, sincerity, and righteous intent',
    pooja_days_title: 'Auspicious Days for Bhairav Pooja',
    pooja_materials_title: 'Pooja Samagri (Materials Required)',
    pooja_steps_title: 'Complete Pooja Procedure',
    pooja_steps_sub: 'Shodashopachara Puja (16-Step Worship) adapted for Kaal Bhairav',
    pooja_effects_title: 'Known Spiritual Effects',
    pooja_card1_title: 'Kaal Bhairav Ashtami', pooja_card1_text: 'The most sacred day — Krishna Paksha Ashtami of Margashirsha month (November–December). The day Bhairav manifested from Shiva. The most powerful day for all Bhairav practices.',
    pooja_card2_title: 'Sunday (Ravivar)', pooja_card2_text: 'Kaal Bhairav\'s primary weekly day. Perform pooja on Sunday for general blessings, protection, and removal of obstacles. Bhairav\'s energy is strongest on this day.',
    pooja_card3_title: 'Ashtami Tithi', pooja_card3_text: 'Both Krishna (dark) and Shukla (bright) Ashtami tithis every month are sacred to Bhairav. Perform pooja or at minimum chant his mantra on every 8th lunar day.',
    pooja_card4_title: 'Tuesday (Mangalvar)', pooja_card4_text: 'Also considered auspicious for Bhairav. Particularly good for Ruru Bhairav and Chanda Bhairav worship — for removing enemies, legal troubles, and health issues.',
    pooja_card5_title: 'Amavasya (New Moon)', pooja_card5_text: 'The dark moon night is especially powerful for Tantric Bhairav practices. Bhairav is a deity of the night, and new moon intensifies his energy significantly.',
    pooja_card6_title: 'Midnight (Nishitha Kaal)', pooja_card6_text: 'The midnight hour (approximately 11:30 PM–12:30 AM) is considered Bhairav\'s most powerful time. Advanced practitioners perform sadhana at this hour.',
    pooja_eff1_title: 'Protection', pooja_eff1_text: 'Regular worship creates a powerful protective shield against enemies, evil spirits, negative energies, and unexpected dangers.',
    pooja_eff2_title: 'Justice &amp; Legal Matters', pooja_eff2_text: 'Bhairav is the Kotwal — the divine administrator of justice. He assists in legal disputes, court cases, and situations where truth needs to prevail.',
    pooja_eff3_title: 'Freedom from Fear', pooja_eff3_text: 'Kaal Bhairav is the ultimate destroyer of fear. Regular devotion dissolves anxiety, phobias, and existential fear — particularly the fear of death.',
    pooja_eff4_title: 'Mental Clarity', pooja_eff4_text: 'Bhairav cuts through confusion and delusion. Devotees report increased clarity, decisive thinking, and removal of mental obstacles.',
    pooja_eff5_title: 'Obstacle Removal', pooja_eff5_text: 'Bhairav clears the path — both materially (job, career, relationship obstacles) and spiritually (karmic blocks, past-life baggage).',
    pooja_eff6_title: 'Spiritual Liberation', pooja_eff6_text: 'The highest effect — Bhairav grants liberation from the cycle of rebirth. As Kotwal of Kashi, he ultimately grants moksha to sincere devotees.',

    // MANTRA PAGE
    mantra_header: 'Mantras &amp; Tantra',
    mantra_sub: 'Sacred syllables of Kaal Bhairav — for devotion, protection, and liberation',
    mantra_mool_title: 'Mool Mantra (Root Mantra)',
    mantra_batuk_title: 'Batuk Bhairav Mantra',
    mantra_gayatri_title: 'Kaal Bhairav Gayatri Mantra',
    mantra_beej_title: 'Beej Mantras (Seed Syllables)',
    mantra_ashtakam_title: 'Kaal Bhairav Ashtakam',
    mantra_tantric_title: 'Tantric Practices',
    mantra_disc_title: '⚠ Guidance on Mantra Practice',
    mantra_disc_text: 'Mantras are sacred sound formulas with deep vibrational energy. They should be practiced with sincerity, regularity, and righteous intent. <strong>Never use any mantra or Tantric practice to harm another person</strong> — this is explicitly forbidden in all authentic Shaiva and Tantric traditions and will create severe negative karma for the practitioner. For Tantric practices beyond basic mantra japa, guidance from a qualified guru is strongly recommended.',
    mantra_mool_how_title: 'How to Practice',
    mantra_mool_how_text: 'Chant 108 times daily using a Rudraksha mala. Best time: Sunday mornings, Tuesday evenings, or midnight. Face South (Bhairav\'s direction). Sit in a clean place with a lamp lit. Results: protection, fear removal, obstacle clearing. Regular practice over 40 days (a <em>mandala</em>) creates noticeable effects.',
    mantra_batuk_sub: 'Batuk = the eternal youth form of Bhairav — most accessible for all devotees',
    mantra_batuk_desc: 'This is one of the most popular and accessible Bhairav mantras. Chant 108 times minimum. Very effective for removing sudden dangers, health crises, travel safety, and sudden reversals of fortune. Source: <em>Batuk Bhairav Tantram</em>.',
    mantra_beej_sub: 'Beej mantras are concentrated vibrational seeds — powerful and direct. For advanced practitioners.',
    mantra_beej1_title: 'Bhairav Beej',
    mantra_beej1_text: '<em>Hreem</em> — the primary beej of Bhairav. Represents his shakti, maya-piercing energy, and direct connection to cosmic consciousness. Used in Tantra as the core seed syllable.',
    mantra_beej2_title: 'Kaal Beej',
    mantra_beej2_text: '<em>Kreem</em> — the beej of Kali, the time-force. Used in Kaal Bhairav practice to invoke the aspect of time-transcendence and dissolution of karma.',
    mantra_beej3_title: 'Mrityu Beej',
    mantra_beej3_text: '<em>Om</em> — the universal sound, the beej of all mantras. Always precedes Bhairav mantras to establish cosmic resonance.',
    mantra_ashtakam_sub: 'The celebrated hymn of 8 verses by Adi Shankaracharya — the most complete devotional text on Kaal Bhairav',
    mantra_ashtakam_desc: 'The complete Ashtakam is an ancient Sanskrit text of 8 stanzas describing the glory, attributes, and grace of Kaal Bhairav. Below is a description of each verse with its meaning and significance. The full Sanskrit text is found in <em>Shankaracharya\'s Stotra Sangraha</em>.',
    mantra_tantric_warn_title: '⚠ Critical Warning on Tantric Practices',
    mantra_tantric_warn_text: 'The following information is provided for <strong>educational purposes only</strong>. Tantric practices described here should <strong>only</strong> be performed by individuals who have received initiation (<em>diksha</em>) from a qualified Shaiva or Tantric guru. Performing Tantric rites without proper initiation, preparation, or guidance can have adverse effects. <strong>All practices are exclusively for personal spiritual benefit — NEVER for harming others.</strong> This website and its creators bear no responsibility for any outcomes.',
    mantra_tantric1_title: 'Shmashana Sadhana',
    mantra_tantric1_text: 'Advanced practice performed in cremation grounds at midnight. Requires proper initiation, fearlessness, and guidance. Considered the most direct way to experience Bhairav\'s presence. Only for initiated Tantrics.',
    mantra_tantric2_title: 'Bhairav Yantra',
    mantra_tantric2_text: 'A geometric diagram (yantra) representing Bhairav\'s cosmic form. It is energized through mantra and ritual and kept in the worship space. Acts as a permanent focal point of Bhairav\'s energy for protection and blessings.',
    mantra_tantric3_title: 'Purashcharana',
    mantra_tantric3_text: 'A dedicated repetition of Bhairav\'s mantra — 100,000 times (1 lakh) minimum for basic activation, typically done over 40 days. Requires specific dietary, behavioral, and ritual restrictions throughout the period.',
    mantra_tantric4_title: 'Amavasya Sadhana',
    mantra_tantric4_text: 'Special practice performed on the new moon night. Begins at midnight. Includes mantra japa, lamp offering, and offerings of sesame and iron. Considered highly potent for removing stubborn obstacles.',
    mantra_final_title: 'The Core Principle of Righteous Practice',
    mantra_final_text: 'All authentic Shaiva Tantric traditions agree: <strong>Bhairav himself punishes those who misuse his energy.</strong> He is the Kotwal of cosmic justice. Using any practice for manipulation, control, or harm of others will invoke Bhairav\'s wrath — not his grace. The practitioner who approaches Bhairav with ego, greed, or malice will find their own karma accelerated and amplified. <em>True Bhairav sadhana dissolves the ego — it does not inflate it.</em>',

    // SEVA PAGE
    seva_header: 'Seva &amp; Donation',
    seva_page_sub: 'The dog is Bhairav\'s beloved vahana — seva of his vehicle is seva of the Lord himself',
    seva_why_title: 'The Sacred Dog — Why Dog Seva is Bhairav Seva',
    seva_how_title: 'How to Perform Dog Seva',
    seva_days_title: 'Most Auspicious Days for Dog Seva',
    seva_donate_title: 'Contribute to Dog Seva',
    seva_temple_title: 'Temple Seva — Kaal Bhairav Mandir, Varanasi',
    seva_why_src: 'Source: Kashi Khanda, Skanda Purana; Oral tradition of Kashi priests',
    seva_why_p1: 'The <strong class="text-gold">dog (Shvan)</strong> is not merely a vehicle for Kaal Bhairav — it is an integral symbol of his nature. The dog represents:',
    seva_why_li1: '<strong class="text-gold">Absolute loyalty</strong> — the dog follows its master through all conditions, representing the devotee\'s unwavering devotion to Bhairav',
    seva_why_li2: '<strong class="text-gold">Alertness and vigilance</strong> — Bhairav as Kotwal is always watchful; the dog never sleeps on duty',
    seva_why_li3: '<strong class="text-gold">Perception beyond the veil</strong> — dogs are said to see spirits and perceive what humans cannot; Bhairav roams the cremation grounds with his dog',
    seva_why_li4: '<strong class="text-gold">The outcaste and the divine</strong> — the dog was considered an "impure" animal in caste society, yet Bhairav — who himself lived as an outcast Kapalika — chose the dog as his companion, affirming that the divine transcends human prejudices',
    seva_why_quote: 'Multiple texts confirm: <em>"Jo nahin karwa sakta Kashi Yatra, woh kar le Shvan Seva" — "One who cannot make the pilgrimage to Kashi can earn the same merit by serving dogs."</em> This is the ancient tradition of Kashi.',
    seva_card1_title: 'Daily Feeding',
    seva_card1_text: 'The simplest and most powerful form of seva. Feed a stray dog every day — especially on Sunday, Tuesday, or Bhairav Ashtami. Use cooked food, bread, or quality dog food. A black dog is most auspicious.',
    seva_card2_title: 'Veterinary Care',
    seva_card2_text: 'Treating an injured or sick stray dog — arranging vet care, bandaging wounds, or contributing to a dog\'s treatment — is considered one of the most direct forms of Bhairav puja.',
    seva_card3_title: 'Shelter Support',
    seva_card3_text: 'Supporting dog shelters and rescue organizations financially or with your time is a profound act of seva. Bhairav watches over all street dogs — your seva reaches him directly.',
    seva_card4_title: 'Water in Summer',
    seva_card4_text: 'Place bowls of clean water outside your home for street dogs and birds, especially during hot months. This simple act is considered highly meritorious in Bhairav tradition.',
    seva_card5_title: 'Sterilization Programs',
    seva_card5_text: 'Supporting ABC (Animal Birth Control) programs that humanely sterilize stray dogs reduces suffering. Contributing to such programs is a compassionate and dharmic act.',
    seva_card6_title: 'Simple Kindness',
    seva_card6_text: 'Even acknowledging a dog, petting it with affection, or speaking gently to it is an act of seva. Bhairav is present in the eyes of every dog.',
    seva_table_th1: 'Day / Occasion', seva_table_th2: 'Significance', seva_table_th3: 'Recommended Seva',
    seva_row1_day: 'Kaal Bhairav Ashtami', seva_row1_sig: 'Bhairav\'s most sacred annual day', seva_row1_seva: 'Feed 8 or more dogs; donate to a dog shelter',
    seva_row2_day: 'Every Sunday', seva_row2_sig: 'Bhairav\'s weekly day', seva_row2_seva: 'Feed at least one dog before eating your own food',
    seva_row3_day: 'Ashtami Tithi (monthly)', seva_row3_sig: '8th lunar day — sacred to Bhairav', seva_row3_seva: 'Feed dogs and contribute to their care',
    seva_row4_day: 'Amavasya (New Moon)', seva_row4_sig: 'Night of Bhairav\'s power', seva_row4_seva: 'Leave food out for dogs at night',
    seva_row5_day: 'Diwali / Narak Chaturdashi', seva_row5_sig: 'Night of the ancestors and Bhairav', seva_row5_seva: 'Special feeding of dogs on this night',
    seva_row6_day: 'Shivratri', seva_row6_sig: 'Night of Shiva-Bhairav', seva_row6_seva: 'Combine Shiva pooja with dog feeding',
    seva_donate_heading: 'Support Stray Dog Welfare in the Name of Kaal Bhairav',
    seva_donate_text: 'Your donation contributes to feeding, treating, and sheltering stray dogs — the living vahanas of Lord Kaal Bhairav. Every contribution, however small, is a direct act of devotion and earns the blessings of the Lord of Kashi.',
    seva_donate_select: 'SELECT AMOUNT (₹)',
    seva_donate_contact_note: 'Donation can be made via UPI / Bank Transfer. Contact us at seva@kaalbhairav.org for details.',
    seva_donate_btn: 'Contact for Donation Details',
    seva_donate_amounts: '₹51 feeds 3-5 dogs for a day &nbsp;|&nbsp; ₹108 provides emergency vet care &nbsp;|&nbsp; ₹1008 sponsors a dog\'s monthly care',
    seva_temple_p1: 'The <strong class="text-gold">Kaal Bhairav Temple in Varanasi</strong> (Kaal Bhairav Gali, near Trilochan) is the most important Bhairav shrine in all of India. It is said that no one can permanently settle in Kashi without first obtaining Kaal Bhairav\'s permission — and devotees visit this temple before Kashi Vishwanath.',
    seva_temple_p2: 'Seva at this temple includes: anna-daan (food donation), deepa-daan (lamp donation), abhishek seva, and dog-feeding at the temple premises. The temple priests can arrange specific sevas on your behalf if you cannot visit in person.',
    seva_temple_p3: '<strong class="text-gold">Temple Address:</strong><br>Kaal Bhairav Mandir, Kaal Bhairav Gali,<br>Near Trilochan, Varanasi (Kashi), UP — 221001',
    seva_shrines_title: 'Other Important Bhairav Shrines',

    // DISCLAIMER PAGE
    disc_header: 'Disclaimer &amp; Terms of Use',
    disc_sub: 'Please read carefully before performing any spiritual practice described on this website',

    // NAV
    nav_home: 'Home',
    nav_about: 'About',
    nav_stories: 'Stories',
    nav_64: '64 Bhairavas',
    nav_kashi: 'Kashi',
    nav_pooja: 'Pooja Vidhi',
    nav_mantra: 'Mantra &amp; Tantra',
    nav_seva: 'Dog Seva',
    nav_disclaimer: 'Disclaimer',

    // FOOTER
    footer_tagline: 'Jay Kaal Bhairav · जय काल भैरव · Dogs are sacred to Kaal Bhairav. Be kind to animals.',
    footer_copy: '&copy; ' + new Date().getFullYear() + ' KaalBhairav.org · All Rights Reserved',

    // INDEX — HERO
    hero_title: 'Kaal Bhairav',
    hero_subtitle: 'Kotwal of Kashi · Lord of Time · Destroyer of Ego',
    hero_desc: 'He who carries the skull of Brahma. He who roams the cremation grounds. He who is Time itself — the fierce, compassionate guardian of Varanasi, the eternal city where death is liberation.',
    btn_pooja: 'Pooja Vidhi',
    btn_mantra: 'Mantras &amp; Tantra',
    btn_stories: 'Sacred Stories',

    // INDEX — WHO IS
    who_title: 'Who is Kaal Bhairav?',
    who_p1: '<strong class="text-gold">Kaal Bhairav</strong> (काल भैरव) is the most fierce and powerful manifestation of Lord Shiva. The name combines <em>Kaal</em> (Time/Death) and <em>Bhairav</em> (terrible, fearsome). He is the god who transcends time itself — and simultaneously is Time.',
    who_p2: 'He is depicted as a dark, naked deity adorned with a garland of skulls, holding a skull-cup (<em>kapala</em>), a trident, a drum, and a noose. His vehicle (<em>vahana</em>) is a black dog — a sacred animal representing loyalty, alertness, and the ability to perceive what humans cannot.',
    who_p3: 'In <strong class="text-gold">Varanasi (Kashi)</strong>, he is revered as the <em>Kotwal</em> — the divine police commissioner — who governs the eternal city on behalf of Lord Shiva. No one enters or leaves Kashi without his permission.',
    attr_title: 'Key Attributes',
    attr_h1: 'Attribute', attr_h2: 'Details',
    attr_name: 'Also Known As', attr_name_val: 'Kshetrapala, Kotwal, Dandapani',
    attr_form: 'Form', attr_form_val: 'Fierce aspect (Ugra) of Shiva',
    attr_vahana: 'Vahana', attr_vahana_val: 'Black Dog (Shvan)',
    attr_color: 'Color', attr_color_val: 'Dark blue / Black',
    attr_day: 'Day', attr_day_val: 'Bhairav Ashtami, Sunday, Tuesday',
    attr_dhaam: 'Primary Dhaam', attr_dhaam_val: 'Kaal Bhairav Temple, Varanasi',
    attr_river: 'Sacred River', attr_river_val: 'Shipra (Ujjain), Ganga (Kashi)',
    attr_forms: 'Forms', attr_forms_val: '64 Bhairavas (Ashtabhairav × 8)',

    // INDEX — CARDS
    cards_title: 'Explore the Sacred Knowledge',
    card1_title: 'Sacred Stories',
    card1_text: 'The beheading of Brahma, origin of Kaal Bhairav, the legend of Kashi Kotwal, and stories from Shiva Purana, Skanda Purana, and Tantric texts.',
    card2_title: '64 Forms of Bhairav',
    card2_text: 'The 64 Bhairavas — 8 Ashtabhairavas each commanding 8 sub-forms. Each form governs a specific direction, power, and aspect of cosmic energy.',
    card3_title: 'Pooja Vidhi',
    card3_text: 'Complete step-by-step Kaal Bhairav pooja procedure — materials required, sankalpa, abhishek, naivedya, aarti, and known spiritual effects.',
    card4_title: 'Mantras &amp; Tantra',
    card4_text: 'Mool mantra, Ashtakam, Bhairav Gayatri, beej mantras, and Tantric practices — with proper guidance, effects, and fair-use principles.',
    card5_title: 'Dog Seva &amp; Donation',
    card5_text: 'The dog is Bhairav\'s sacred vahana. Feeding and caring for dogs — especially strays — is one of the highest forms of Bhairav seva.',
    card6_title: 'About Kaal Bhairav',
    card6_text: 'Iconography, significance, connection to Shaivism and Tantra, Bhairav in different traditions — Shaiva, Shakta, and Nath sampradaya.',

    // INDEX — MANTRA
    mantra_title: 'The Mool Mantra',
    mantra_meaning: '"Om Hreem Batukaya Apaduddharanaya Kuru Kuru Batukaya Hreem"<br><em>O Batuk Bhairav, please remove all obstacles and distress from my life.</em>',
    mantra_guide: 'Chant 108 times daily, preferably on Sunday or Tuesday, facing South.',
    btn_copy: 'Copy Mantra',

    // INDEX — KASHI
    kashi_title: 'Kashi — The Eternal City',
    kashi_source: 'Source: Kashi Khanda, Skanda Purana',
    kashi_story_title: 'Why Kaal Bhairav is Kashi\'s Guardian',
    kashi_p1: 'When Lord Shiva decided to make Kashi his permanent abode, he needed an eternal guardian for the city — one who would maintain cosmic order, punish wrongdoers, and ensure that every soul dying within the city\'s limits received liberation (<em>moksha</em>).',
    kashi_p2: 'He appointed <strong class="text-gold">Kaal Bhairav</strong> as the <em>Kotwal</em> — the keeper of Kashi. The Kaal Bhairav temple on Kaal Bhairav Gali in Varanasi is one of the most important shrines in the city, and it is said that one must visit Kaal Bhairav before visiting Kashi Vishwanath — to seek permission to enter the eternal city.',
    kashi_p3: 'According to tradition, even Lord Yama (the god of death) has no authority within the boundaries of Kashi — it is Kaal Bhairav alone who presides over death and liberation here. Every soul departing from Kashi is said to receive the <em>Tarak Mantra</em> whispered in the ear by Lord Shiva himself, through the grace of Kaal Bhairav.',
    btn_all_stories: 'Read All Sacred Stories →',

    // INDEX — DOG SEVA
    seva_title: 'Feed a Dog, Please Bhairav',
    seva_desc: 'The black dog is Kaal Bhairav\'s <em>vahana</em> and most beloved animal. Feeding a stray dog — especially on Sunday, Bhairav Ashtami, or during Kaal Bhairav Jayanti — is considered one of the most powerful acts of devotion.',
    btn_seva: 'Contribute to Dog Seva',

    // INDEX — DISCLAIMER
    disclaimer_title: '⚠ Important Notice — Please Read',
    disclaimer_text: 'All spiritual practices, mantras, and Tantric procedures described on this website are presented for <strong>educational and devotional purposes only</strong>. They are meant exclusively for <strong>personal spiritual growth, protection, and positive purposes</strong>. The use of any practice for harming others is strictly prohibited and goes against the dharmic principles of Bhairav worship. Any practice performed is entirely at the practitioner\'s own responsibility and risk.',
    disclaimer_link: 'Read full disclaimer →',
  },

  hi: {
    // ABOUT PAGE
    about_header: 'काल भैरव का परिचय',
    about_sub: 'प्रतिमा विज्ञान, महत्व और शैवाद की महान परंपराओं में उनका स्थान',
    about_ico_title: 'प्रतिमा विज्ञान — भैरव का स्वरूप',
    about_ico_intro: 'काल भैरव का रूप जानबूझकर इंद्रियों को अभिभूत करने के लिए बनाया गया है — अहंकार का सीधे सामना करने के लिए। उन्हें विभिन्न ग्रंथों में इस प्रकार वर्णित किया गया है:',
    about_weapons_title: 'आठ अस्त्र (अष्टायुध)',
    about_name_title: 'नाम का अर्थ',
    about_card_kaal_title: 'काल (Kaal)',
    about_card_kaal_text: 'का अर्थ है "समय" और "मृत्यु" दोनों। भैरव काल के रूप में साकार समय हैं — वह शक्ति जो सब कुछ विलीन कर देती है। वे एक साथ संहारक और संहार से परे हैं। उन्हें "महाकाल" कहा जाता है — समय से परे।',
    about_card_bhairav_title: 'भैरव (Bhairav)',
    about_card_bhairav_text: '"भीरु" (भय) या "भ-र-व" मूल से — तीन अक्षर प्रतीक हैं: भ = भरण (पालन), र = रमण (विलय), व = वमन (सृजन)। इस प्रकार भैरव एक संपूर्ण ब्रह्मांडीय शक्ति हैं।',
    about_card_kshtra_title: 'क्षेत्रपाल',
    about_card_kshtra_text: 'क्षेत्र (भूमि) के रक्षक — शरीर का क्षेत्र और पवित्र क्षेत्र (मंदिर, श्मशान) दोनों। वे संसारों के बीच की सीमाओं और देहलीज़ों के संरक्षक हैं।',
    about_card_danda_title: 'दंडपाणि',
    about_card_danda_text: 'न्याय के दंड (दंड) के धारक। कोतवाल के रूप में वे दिव्य न्याय का संचालन करते हैं। उनके दंड से कोई आत्मा नहीं बच सकती — हर कार्य दर्ज है और हर कर्म का फल मिलता है।',
    about_shaiva_tag: 'शैव सिद्धांत और शैव आगम',
    about_shaiva_title: 'शैव परंपरा में',
    about_shaiva_text: 'शास्त्रीय शैव परंपरा में भैरव को शिव के सबसे महत्वपूर्ण रूपों में से एक माना जाता है। शैव आगम — 64 प्रमुख ग्रंथ — में <em>भैरवागम</em> सम्मिलित है जो पूर्णतः भैरव पूजा को समर्पित है। भैरव को शिव का "क्रोध-मूर्ति" (धार्मिक क्रोध का रूप) माना जाता है — वह पहलू जो अधर्म को दंडित करता और धर्म की रक्षा करता है।',
    about_kashmir_tag: 'कश्मीर शैवाद (त्रिक)',
    about_kashmir_title: 'कश्मीर शैवाद में',
    about_kashmir_text: 'अभिनवगुप्त और उत्पलदेव के अद्वैत कश्मीर शैवाद में भैरव शुद्ध चेतना का सर्वोच्च प्रतीक हैं — <em>परमशिव</em>। त्रिक परंपरा तीन देवियों (परा, परापरा, अपरा) पर केंद्रित है जिनके भगवान भैरव हैं। अभिनवगुप्त के <em>तंत्रालोक</em> में भैरव को वह सार्वभौमिक चेतना बताया गया है जो सृजन और विलय की लीला के माध्यम से स्वयं का अनुभव करती है। उनका उग्र रूप शुद्ध आनंद (<em>आनंद</em>) के रूप में समझा जाता है — क्रोध नहीं।',
    about_nath_tag: 'नाथ संप्रदाय',
    about_nath_title: 'नाथ परंपरा में',
    about_nath_text: 'गोरखनाथ और नाथ वंश भैरव को आदर्श सिद्ध — वह सिद्ध योगी जिसने शरीर, मन और मृत्यु पर विजय पाई है — के रूप में पूजते हैं। नाथ भैरव साधना को काया-सिद्धि (शारीरिक पूर्णता) और काल-विजय (समय/मृत्यु पर विजय) के मार्ग के रूप में करते हैं। कई नाथ ग्रंथों में भैरव स्वयं गोरखनाथ के गुरु के रूप में प्रकट होते हैं।',
    about_shakta_tag: 'शाक्त परंपरा',
    about_shakta_title: 'भैरव और शाक्त',
    about_shakta_text: 'शाक्त परंपरा में भैरव अपनी शक्ति से अविभाज्य हैं। 64 योगिनियां — शक्तिशाली तांत्रिक देवियां — प्रत्येक का एक संगत भैरव है। 64 भैरव-योगिनी युग्म संपूर्ण तांत्रिक ब्रह्मांड का शासन करते हैं। देवी भागवत और ललिता सहस्रनाम परंपरा में भैरव काल भैरव के रूप में देवी के पवित्र क्षेत्र की बाहरी सीमाओं की रक्षा करते हैं।',
    about_traditions_title: 'विभिन्न परंपराओं में भैरव',
    about_deeper_title: 'गहरी शिक्षा',
    about_deeper_text: 'काल भैरव केवल एक देवता नहीं हैं जिन्हें प्रसन्न किया जाए — वे एक दर्पण हैं। जब आप उनके सामने खड़े होते हैं, तो आप देखते हैं कि आप वास्तव में क्या हैं: एक अस्थायी शरीर में चेतना, समय के साथ चलती हुई, अंततः अनंत में विलीन होने के लिए। जो खोपड़ियां वे पहनते हैं, वे उन सभी अहंकारों की हैं जो आपसे पहले आए।<br><br>उनका उपहार धन या शक्ति नहीं है — यह <em>निर्भयता</em> है। भैरव को जानना यह जानना है कि कुछ भी वास्तव में आत्मा को हानि नहीं पहुंचा सकता। काल सभी रूपों को नष्ट करता है — लेकिन आप एक रूप नहीं हैं। आप वह हैं जो रूपों को उठते और विलीन होते हुए देखते हैं।<br><br><em class="text-gold">यही काल भैरव की सर्वोच्च शिक्षा है।</em>',

    // STORIES PAGE
    stories_header: 'पवित्र कथाएं',
    stories_sub: 'शिव पुराण, स्कंद पुराण, लिंग पुराण और तांत्रिक ग्रंथों की पौराणिक कथाएं',
    story1_src: 'स्रोत: शिव पुराण — शतरुद्र संहिता; स्कंद पुराण — काशी खंड',
    story1_title: 'काल भैरव का जन्म — ब्रह्मा का शिरच्छेदन',
    story1_body: 'आदि युग में सृष्टिकर्ता ब्रह्मा और पालक विष्णु के बीच सर्वोच्चता को लेकर महान विवाद उठा। दोनों ने स्वयं को परम सत्य घोषित किया। उसी क्षण उनके मध्य अग्नि का एक दीप्तिमान स्तंभ प्रकट हुआ — अनंत, जिसका न आदि था न अंत। यह <em>ज्योतिर्लिंग</em> के रूप में भगवान शिव थे।<br><br>ब्रह्मा और विष्णु सहमत हुए: जो इस स्तंभ का अंत खोज ले वही सर्वोच्च है। विष्णु वराह रूप में नीचे गए, ब्रह्मा हंस रूप में ऊपर उड़े। विष्णु हजारों वर्ष खोजते रहे पर तल न मिला। विनम्र होकर उन्होंने शिव की सर्वोच्चता स्वीकार की।<br><br>किंतु ब्रह्मा के पाँचों मस्तकों के संयुक्त अहंकार ने उन्हें घेर लिया। ऊपर जाते समय एक <em>केतकी</em> का फूल नीचे आता मिला। ब्रह्मा ने पूछा कहाँ से आया। फूल ने कहा हजारों वर्षों से स्तंभ के शीर्ष से बहता आ रहा हूँ। ब्रह्मा ने फूल से झूठ बोलवाने का समझौता किया — कि ब्रह्मा शीर्ष तक पहुँच गए।<br><br>जब ब्रह्मा ने शिव के सम्मुख झूठी विजय घोषित की, <em>सर्वज्ञ</em> शिव इस सत्य-ब्रह्महत्या पर ब्रह्मांडीय क्रोध से भर उठे। उनका क्रोध एक भयावह रूप बन गया: <strong class="text-gold">काल भैरव</strong>।<br><br>काल भैरव शिव के तीसरे नेत्र से प्रकट हुए — आंधी के बादल सा काला रूप, जलती आँखें, खोपड़ियों की माला, हाथ में त्रिशूल और कपाल। एक पल में उन्होंने ब्रह्मा का पाँचवाँ सिर काट दिया — वह सिर जिसने झूठ बोला, जो मिथ्या अहंकार और घमंड का प्रतीक था।<br><br>किंतु शिव के रूप होने पर भी भैरव ने <em>ब्रह्महत्या</em> का पाप किया। ब्रह्मा की कटी खोपड़ी उनके हाथ से चिपक गई और हटती न थी। इसीलिए भैरव <em>कपाल</em> धारण करते हैं। वे एक भटकते तपस्वी, कापालिक बन गए।<br><br>वे ब्रह्मांड के सभी तीर्थों पर भटकते रहे। जहाँ भी गए, खोपड़ी साथ रही। अंततः <strong class="text-gold">काशी (वाराणसी)</strong> पहुँचे। काशी की धरती पर पाँव रखते ही खोपड़ी गिर गई। ब्रह्महत्या का महापाप क्षमा हो गया। इसीलिए काशी सभी पापों की परम मुक्तिदाता है — काल भैरव का पाप भी यहाँ धुल गया।<br><br>काशी की पवित्रता से प्रेरित होकर, और भगवान शिव के अनुरोध पर, भैरव सदा के लिए काशी में <em>कोतवाल</em> — दिव्य संरक्षक और शाश्वत नगरी के प्रशासक — बन कर रहे।',
    story2_src: 'स्रोत: स्कंद पुराण — काशी खंड, अध्याय 31',
    story2_title: 'भैरव काशी के कोतवाल बने',
    story2_body: 'काशी में पाप से मुक्ति के बाद काल भैरव विश्वनाथ के महालिंग रूप में शिव के सम्मुख खड़े हुए। शिव भैरव की तपस्या और ब्रह्मा के अहंकार को दंडित करने के धर्मपूर्ण कार्य से प्रसन्न हुए और बोले:<br><br><em style="border-left:2px solid var(--gold); padding-left:1rem; display:block; color:var(--gold-pale);">"तुम इस नगरी के शाश्वत कोतवाल रहोगे। बिना तुम्हारे ज्ञान के कोई आत्मा काशी में प्रवेश न करे, न जाए। तुम यहाँ मेरे प्रतिनिधि हो। जो भक्ति से तुम्हारी पूजा करेंगे, वे सभी भयों और पुनर्जन्म के चक्र से मुक्त होंगे।"</em><br><br>उस दिन से काल भैरव काशी में रहने लगे। वे अपने कुत्ते के साथ श्मशान घाटों पर — विशेषकर <strong class="text-gold">मणिकर्णिका घाट</strong> पर — विचरण करते हैं। वे काशी में हर मरते व्यक्ति के कान में <em>तारक मंत्र</em> फुसफुसाते हैं, उसके पिछले कर्मों की परवाह किए बिना उसे तत्काल मोक्ष देते हैं।<br><br>उनका <em>दंड</em> उनके अधिकार का प्रतीक है। वे न्याय का दंड, दुष्टों को बाँधने की पाश और प्रयाण करने वाली आत्माओं को अर्पण करने का कपाल लिए रहते हैं। वे एक साथ <em>दंडपाणि</em> (दंड के धारक) और उन आत्माओं के सबसे करुणामय मुक्तिदाता हैं जो उनकी शरण में आती हैं।',
    story3_src: 'स्रोत: लिंग पुराण; तांत्रिक परंपरा',
    story3_title: 'काल भैरव और राक्षस दुर्गामा',
    story3_body: 'राक्षस दुर्गामा ने कठोर तपस्या करके ब्रह्मा से वरदान प्राप्त किया कि उसे कोई देव, मनुष्य या प्राणी न मार सके — केवल बच्चा (<em>बाल</em>) या बुजुर्ग (<em>वृद्ध</em>) को छोड़कर। इस वरदान से दुर्गामा ने तीनों लोकों में आतंक फैलाया, देवों को उनके आवासों से खदेड़ दिया।<br><br>देवगण सहायता के लिए भगवान शिव के पास गए। शिव ने भैरव को <strong class="text-gold">बटुक भैरव</strong> — एक नवयुवक, शाश्वत 16 वर्षीय बालक — के रूप में प्रकट किया। इस बालक रूप में भैरव खेलते-खेलते दुर्गामा के पास गए, मानो कोई खतरा हो ही नहीं। राक्षस बच्चे को देखकर हँसा और आक्रमण किया — पर एक ही पल में बटुक भैरव के त्रिशूल से मारा गया।<br><br>यह कथा सिखाती है कि सबसे भयंकर शक्ति सबसे सरल, विनम्र रूप में निवास कर सकती है। बटुक भैरव की पूजा विशेषकर बच्चों और घरों की सुरक्षा के लिए होती है और उनका मंत्र बाधाओं और शत्रुओं को हटाने में अत्यंत शक्तिशाली माना जाता है।',
    story4_src: 'स्रोत: उत्तर कालामृत; काशी कोतवाल की मौखिक परंपरा',
    story4_title: 'पवित्र कुत्ता — भैरव का वाहन',
    story4_body: 'काशी की मौखिक परंपरा में एक कथा है कि कुत्ता भैरव का वाहन क्यों बना। एक बार काशी के ब्राह्मण पुजारी अपनी जाति के गर्व में अंधे हो गए और मंदिर के पास भूखे कुत्ते को खाना देने से मना कर दिया। कुत्ता भूख से मरने की कगार पर था।<br><br>उस रात भगवान शिव ने प्रधान पुजारी के स्वप्न में भैरव रूप में प्रकट होकर कहा: <em>"वह कुत्ता मेरा शरीर है। तुमने मुझे भूखा रखा। जो कुत्ता आवारा लगता है — उसमें मैं निवास करता हूँ। जो मेरे कुत्ते को खिलाता है, मुझे खिलाता है। जो उसे कष्ट देता है, मुझे कष्ट देता है।"</em><br><br>तब से काशी में कुत्तों को खिलाना — विशेषकर काले कुत्तों को — भैरव सेवा का पवित्र आचरण बन गया। यह परंपरा आज भी जारी है। रात में <em>कुत्ते का रोना</em> भैरव की उपस्थिति का संकेत माना जाता है।',
    story5_src: 'स्रोत: सिद्ध तंत्र परंपरा; अभिनवगुप्त का तंत्रालोक',
    story5_title: 'भैरव और कापालिक परंपरा',
    story5_body: 'ब्रह्मा का शिरच्छेदन करने के बाद भैरव प्रथम <em>कापालिक</em> तपस्वी के रूप में भटकते रहे — खोपड़ी लिए, परम पाप का बोझ उठाए, सभी सामाजिक नियमों के बाहर जीते हुए। वे खोपड़ी से खाते थे, श्मशान उनका घर था, खोपड़ियाँ उनके आभूषण थे।<br><br>कापालिक परंपरा — सबसे प्राचीन तांत्रिक संप्रदायों में से एक — ने भैरव को अपना आराध्य देव माना और उनकी भटकती तपस्या का अनुकरण किया। वे श्मशान में साधना करते, कपाल-पात्र उपयोग करते और वामाचार तांत्रिक मार्ग का अनुसरण करते।<br><br>गहरा प्रतीकवाद अत्यंत गहन है: भैरव ब्रह्मा की खोपड़ी लिए यह दिखाने के लिए कि <em>सृष्टि का सबसे महान अहंकार भी</em> एक खाली पात्र बन जाता है — भैरव के लिए एक साधारण कटोरा। खोपड़ी व्यक्तिगत पहचान के ब्रह्मांडीय चेतना में विलय का प्रतीक है। यही काल भैरव की मूल शिक्षा है: <em>अहंकार ही एकमात्र वास्तविक पाप है, और काल सभी अहंकारों को नष्ट करता है।</em>',
    btn_explore_64: '64 भैरव रूप देखें →',
    btn_pooja_vidhi: 'पूजा विधि →',

    // 64 BHAIRAV PAGE
    bhairav64_header: 'भैरव के 64 रूप',
    bhairav64_sub: 'अष्टभैरव और उनके रूप — ब्रह्मांड की आठ दिशाओं के संरक्षक',
    bhairav64_intro_title: '64 भैरवों को समझना',
    bhairav64_list_title: 'पूर्ण सूची — सभी 64 भैरव',
    bhairav64_list_sub: 'भैरवागम और रुद्रयामल तंत्र में वर्णित',
    bhairav64_8_title: 'आठ अष्टभैरव',
    bhairav64_sources_title: '📚 ग्रंथ स्रोत',
    bhairav64_intro_p1: 'शैव तांत्रिक परंपरा (विशेषतः <em>भैरवागम</em> और <em>रुद्रयामल तंत्र</em>) के अनुसार, <strong class="text-gold">64 भैरव</strong> हैं जो 8 प्रमुख रूपों में संगठित हैं, जिन्हें <strong class="text-gold">अष्टभैरव</strong> कहा जाता है। इन 8 प्रमुख भैरवों में से प्रत्येक के 8 उप-रूप हैं — इस प्रकार 8 × 8 = 64। वे सामूहिक रूप से ब्रह्मांड की 8 दिशाओं, 8 श्मशान भूमियों (<em>अष्ट श्मशान</em>), और तांत्रिक शक्ति के 8 पहलुओं (<em>अष्ट सिद्धि</em>) पर अधिकार रखते हैं।',
    bhairav64_intro_p2: 'काशी (वाराणसी) में अष्टभैरव नगर के चारों ओर 8 बिंदुओं पर स्थित हैं, जो एक पवित्र सुरक्षा कवच बनाते हैं — <em>काशी अष्टभैरव चक्र</em> — जो पवित्र नगरी की रक्षा करता है। काशी के सभी 8 भैरव मंदिरों की तीर्थ यात्रा अत्यंत शुभ मानी जाती है।',
    bhairav64_sources_text: '64 भैरवों की गणना और विवरण मुख्यतः इन ग्रंथों में मिलते हैं:',

    // KASHI PAGE
    kashi_header: 'काल भैरव और काशी',
    kashi_page_sub: 'शाश्वत नगरी और उसका ब्रह्मांडीय संरक्षक — अनादि काल से अटूट बंधन',
    kashi_intro_title: 'काशी — वह नगरी जो कभी नहीं सोती',
    kashi_kotwal_title: 'कोतवाल — दिव्य पुलिस आयुक्त',
    kashi_powers_title: 'काशी में भैरव की शक्तियां',
    kashi_temple_title: 'काल भैरव मंदिर — वाराणसी',
    kashi_moksha_title: 'काशी मोक्ष क्यों देती है',
    kashi_ashta_title: 'काशी के आठ भैरव',
    kashi_intro_p1: '<strong class="text-gold">काशी (वाराणसी)</strong> केवल एक नगर नहीं — यह एक ब्रह्मांडीय धुरी है, एक ऐसा स्थान जहाँ जीवित संसार और परलोक के बीच की सीमाएँ स्थायी रूप से पतली हैं। स्कंद पुराण के <em>काशी खंड</em> के अनुसार, काशी भगवान शिव के त्रिशूल की नोक पर खड़ी है — स्वर्ग और पृथ्वी के बीच निलंबित, कभी वास्तव में धरती को नहीं छूती।',
    kashi_intro_p2: 'इस पवित्र नगरी में मृत्यु स्वयं मोक्ष बन जाती है। काशी से प्रयाण करने वाली प्रत्येक आत्मा को <strong class="text-gold">तारक मंत्र</strong> — पार करने का मंत्र — स्वयं भगवान शिव द्वारा सीधे कान में फुसफुसाया जाता है। इसीलिए काशी हजारों वर्षों से तीर्थयात्रियों, तपस्वियों और मरणासन्न लोगों का गंतव्य रही है।',
    kashi_intro_p3: 'किंतु काशी को एक संरक्षक की आवश्यकता है — एक शाश्वत कोतवाल — जो इसकी ब्रह्मांडीय व्यवस्था बनाए रखे, सीमाओं की रक्षा करे, और यह सुनिश्चित करे कि मोक्ष की कृपा के बिना कोई आत्मा न जाए। वह संरक्षक हैं <strong class="text-gold">काल भैरव</strong>।',
    kashi_kotwal_src: 'स्रोत: काशी खंड, स्कंद पुराण; लिंग पुराण',
    kashi_kotwal_story: 'काल भैरव काशी के कोतवाल कैसे बने',
    kashi_kotwal_body: 'जब भगवान शिव ने काशी को अपना स्थायी आवास चुना, तो उन्हें एक ऐसे संरक्षक की नियुक्ति करनी थी जो पूर्ण अधिकार से शाश्वत नगरी का शासन करे। नगरी को ऐसे देवता की आवश्यकता थी जो देव, दानव और मनुष्य सभी से सम्मान पाए।<br><br>शिव ने <strong class="text-gold">काल भैरव</strong> को काशी का <em>क्षेत्रपाल</em> (क्षेत्र का रक्षक) और <em>कोतवाल</em> (दिव्य आयुक्त) नियुक्त किया। "कोतवाल" की उपाधि महत्वपूर्ण है — प्राचीन भारत में कोतवाल नगर का मुख्य न्याय अधिकारी था। भैरव काशी की हर आत्मा का ब्रह्मांडीय रजिस्टर रखते हैं।<br><br><em>काशी खंड</em> में कहा गया है: <em>"काशी के कोतवाल काल भैरव के दर्शन बिना, काशी विश्वनाथ की यात्रा अधूरी है।"</em> इसीलिए आज भी भक्त काशी विश्वनाथ जाने से पहले काल भैरव मंदिर जाते हैं।',
    kashi_card1_title: 'ब्रह्मांडीय विधि के रक्षक',
    kashi_card1_text: 'भैरव काशी में प्रवेश करने वाली हर आत्मा को पंजीकृत करते हैं। उनकी अनुमति के बिना कोई नगरी में स्थायी रूप से नहीं रह सकता — यह प्राचीन परंपरा आज भी वाराणसी में बसने वालों द्वारा मानी जाती है।',
    kashi_card2_title: 'मोक्ष के स्वामी',
    kashi_card2_text: 'काशी की सीमाओं के भीतर स्वयं यमराज (मृत्यु के देव) का कोई अधिकार नहीं। यहाँ केवल भैरव मृत्यु पर अधिकार रखते हैं, और वे सुनिश्चित करते हैं कि हर प्रयाण करने वाली आत्मा को मोक्ष मिले।',
    kashi_card3_title: 'नगरी के रक्षक',
    kashi_card3_text: 'भैरव काशी की गलियों में विचरण करते हैं, विशेषकर रात में, नकारात्मक शक्तियों, दुष्ट आत्माओं और नगरी की पवित्र शांति को भंग करने वालों से रक्षा करते हुए।',
    kashi_card4_title: 'तीर्थ का द्वार',
    kashi_card4_text: 'प्राचीन परंपरा के अनुसार काशी के भीतर कोई भी तीर्थ करने से पहले भैरव की अनुमति लेनी होती है। उनके दर्शन नगरी के गहरे आध्यात्मिक आशीर्वाद का द्वार खोलते हैं।',
    kashi_card5_title: 'रात्रि के स्वामी',
    kashi_card5_text: 'भैरव काशी में मध्यरात्रि से भोर तक सबसे सक्रिय रहते हैं। मणिकर्णिका और हरिश्चंद्र घाट के श्मशान उनका राज्य हैं — जहाँ वे जीवन और मृत्यु के संक्रमण की अध्यक्षता करते हैं।',
    kashi_card6_title: 'शिव के प्रतिनिधि',
    kashi_card6_text: 'भैरव काशी में शिव के प्रत्यक्ष प्रतिनिधि हैं। भैरव का सम्मान करना शिव का सम्मान करना है — काशी की पवित्र भूगोल में दोनों को अभिन्न माना जाता है।',
    kashi_temple_p1: 'वाराणसी की काल भैरव गली में <strong class="text-gold">काल भैरव मंदिर</strong> भारत का सबसे महत्वपूर्ण भैरव मंदिर है। यहाँ देवता की पूजा काशी के सर्वोच्च शासक के रूप में होती है — प्रतिदिन हजारों भक्त दर्शन करते हैं।',
    kashi_temple_p2: 'इस मंदिर की सबसे विशिष्ट विशेषता <strong class="text-gold">मद्य (मदिरा)</strong> का चढ़ावा है — यहाँ के देवता नैवेद्य के रूप में मदिरा स्वीकार करते और ग्रहण करते हैं। यह एक दुर्लभ और प्राचीन तांत्रिक परंपरा है।',
    kashi_temple_p3: 'मंदिर में एक पवित्र <strong class="text-gold">काला कुत्ता</strong> भी है — भैरव का वाहन। इस कुत्ते को खिलाना और सम्मान देना भैरव की प्रत्यक्ष भक्ति माना जाता है।',
    kashi_moksha_src: 'स्रोत: काशी खंड, स्कंद पुराण; शिव पुराण',
    kashi_moksha_story: 'तारक मंत्र और भैरव की भूमिका',
    kashi_moksha_body: '<em>काशी खंड</em> एक दिव्य व्यवस्था का वर्णन करता है: काशी की सीमाओं — <em>पंचकोशी</em> — के भीतर मरने वाली हर आत्मा को मोक्ष मिलता है। यह मोक्ष एक विशेष तंत्र द्वारा होता है। मृत्यु के क्षण में स्वयं भगवान शिव प्रकट होते हैं और मरने वाले के कान में <em>तारक मंत्र</em> फुसफुसाते हैं।<br><br>किंतु यह पवित्र व्यवस्था <strong class="text-gold">काल भैरव</strong> द्वारा बनाए रखी और संरक्षित है। वही सुनिश्चित करते हैं कि कोई नकारात्मक शक्ति इस प्रक्रिया को बाधित न करे। कोतवाल इस अर्थ में मोक्ष के प्रशासक हैं।<br><br>इसीलिए परंपरा कहती है: <em>"काशी में मरा, तो मुक्ति मिली।"</em> किंतु इस मुक्ति के पीछे काल भैरव खड़े हैं — वह अदृश्य संरक्षक जो काशी के वचन को सत्य बनाते हैं।',
    kashi_closing: 'काशी और भैरव एक हैं। नगरी उनका शरीर है — गंगा उसकी जीवन-रेखा, घाट उनके चरण-चिह्न, चिता की लपटें उनकी आंखें। काशी में चलना भैरव के भीतर ही चलना है।<br><br>हर संकरी गली, सांझ को जलती हर दीप, दशाश्वमेध पर उठता हर जयघोष — सब उनकी उपस्थिति से गूंजता है। वे हर आत्मा को देखते हैं, हर कर्म जानते हैं, और चुपचाप हर एक को मोक्ष की ओर ले जाते हैं।<br><br><em class="text-gold">जय काल भैरव। जय काशी विश्वनाथ।</em>',
    btn_read_stories: 'पवित्र कथाएं पढ़ें →',

    // POOJA VIDHI PAGE
    pooja_header: 'पूजा विधि',
    pooja_sub: 'पूर्ण पूजा प्रक्रिया — भक्ति, निष्ठा और धर्मपूर्ण संकल्प के साथ',
    pooja_days_title: 'भैरव पूजा के शुभ दिन',
    pooja_materials_title: 'पूजा सामग्री (आवश्यक वस्तुएं)',
    pooja_steps_title: 'पूर्ण पूजा प्रक्रिया',
    pooja_steps_sub: 'काल भैरव के लिए अनुकूलित षोडशोपचार पूजा (16 चरण)',
    pooja_effects_title: 'आध्यात्मिक प्रभाव',
    pooja_card1_title: 'काल भैरव अष्टमी', pooja_card1_text: 'सबसे पवित्र दिन — मार्गशीर्ष मास की कृष्ण पक्ष अष्टमी (नवम्बर-दिसम्बर)। वह दिन जब भैरव शिव से प्रकट हुए। सभी भैरव साधनाओं के लिए सबसे शक्तिशाली दिन।',
    pooja_card2_title: 'रविवार (Ravivar)', pooja_card2_text: 'काल भैरव का प्राथमिक साप्ताहिक दिन। रविवार को पूजा करने से सामान्य आशीर्वाद, सुरक्षा और बाधाओं का निवारण होता है। इस दिन भैरव की ऊर्जा सबसे प्रबल होती है।',
    pooja_card3_title: 'अष्टमी तिथि', pooja_card3_text: 'प्रत्येक माह की कृष्ण और शुक्ल दोनों अष्टमी तिथियाँ भैरव को पवित्र हैं। प्रत्येक 8वें चन्द्र दिवस पर कम से कम उनका मंत्र जप करें।',
    pooja_card4_title: 'मंगलवार (Mangalvar)', pooja_card4_text: 'भैरव के लिए शुभ माना जाता है। रुरु भैरव और चण्ड भैरव की पूजा के लिए विशेष रूप से अच्छा — शत्रुओं, कानूनी परेशानियों और स्वास्थ्य समस्याओं को दूर करने के लिए।',
    pooja_card5_title: 'अमावस्या (नई चंद्रमा)', pooja_card5_text: 'काली रात तांत्रिक भैरव साधनाओं के लिए विशेष रूप से शक्तिशाली है। भैरव रात के देवता हैं और अमावस्या उनकी ऊर्जा को काफी बढ़ा देती है।',
    pooja_card6_title: 'मध्यरात्रि (निशीथ काल)', pooja_card6_text: 'मध्यरात्रि का समय (लगभग 11:30 PM–12:30 AM) भैरव का सबसे शक्तिशाली समय माना जाता है। उन्नत साधक इस समय साधना करते हैं।',
    pooja_eff1_title: 'सुरक्षा', pooja_eff1_text: 'नियमित पूजा शत्रुओं, दुष्ट आत्माओं, नकारात्मक ऊर्जाओं और अप्रत्याशित खतरों से एक शक्तिशाली सुरक्षा कवच बनाती है।',
    pooja_eff2_title: 'न्याय और कानूनी मामले', pooja_eff2_text: 'भैरव कोतवाल हैं — न्याय के दिव्य प्रशासक। वे कानूनी विवादों, अदालती मामलों और जहाँ सत्य को विजयी होना हो उन स्थितियों में सहायता करते हैं।',
    pooja_eff3_title: 'भय से मुक्ति', pooja_eff3_text: 'काल भैरव भय के परम नाशक हैं। नियमित भक्ति चिंता, फोबिया और अस्तित्वगत भय — विशेषकर मृत्यु का भय — को दूर करती है।',
    pooja_eff4_title: 'मानसिक स्पष्टता', pooja_eff4_text: 'भैरव भ्रम और मोह को काट देते हैं। भक्त बढ़ी हुई स्पष्टता, निर्णायक सोच और मानसिक बाधाओं के निवारण की सूचना देते हैं।',
    pooja_eff5_title: 'बाधा निवारण', pooja_eff5_text: 'भैरव मार्ग को साफ करते हैं — भौतिक (नौकरी, करियर, संबंध बाधाएं) और आध्यात्मिक (कर्म अवरोध, पूर्व जन्म के बोझ) दोनों।',
    pooja_eff6_title: 'आध्यात्मिक मोक्ष', pooja_eff6_text: 'सर्वोच्च प्रभाव — भैरव पुनर्जन्म के चक्र से मुक्ति देते हैं। काशी के कोतवाल के रूप में वे अंततः निष्ठावान भक्तों को मोक्ष प्रदान करते हैं।',

    // MANTRA PAGE
    mantra_header: 'मंत्र और तंत्र',
    mantra_sub: 'काल भैरव के पवित्र बीज — भक्ति, सुरक्षा और मोक्ष के लिए',
    mantra_mool_title: 'मूल मंत्र',
    mantra_batuk_title: 'बटुक भैरव मंत्र',
    mantra_gayatri_title: 'काल भैरव गायत्री मंत्र',
    mantra_beej_title: 'बीज मंत्र (बीज अक्षर)',
    mantra_ashtakam_title: 'काल भैरव अष्टकम',
    mantra_tantric_title: 'तांत्रिक साधनाएं',
    mantra_disc_title: '⚠ मंत्र साधना पर मार्गदर्शन',
    mantra_disc_text: 'मंत्र गहरी कंपन ऊर्जा वाले पवित्र ध्वनि सूत्र हैं। इन्हें निष्ठा, नियमितता और धर्मपूर्ण संकल्प के साथ साधना चाहिए। <strong>किसी अन्य व्यक्ति को हानि पहुंचाने के लिए किसी भी मंत्र या तांत्रिक साधना का उपयोग कभी न करें</strong> — यह सभी प्रामाणिक शैव और तांत्रिक परंपराओं में स्पष्ट रूप से वर्जित है और साधक के लिए गंभीर नकारात्मक कर्म उत्पन्न करेगा। मूल मंत्र जप से आगे की तांत्रिक साधनाओं के लिए योग्य गुरु का मार्गदर्शन दृढ़ता से अनुशंसित है।',
    mantra_mool_how_title: 'साधना विधि',
    mantra_mool_how_text: 'रुद्राक्ष माला से प्रतिदिन 108 बार जप करें। सर्वोत्तम समय: रविवार प्रातः, मंगलवार सायंकाल, या मध्यरात्रि। दक्षिण दिशा (भैरव की दिशा) की ओर मुख करें। दीप जलाकर स्वच्छ स्थान पर बैठें। परिणाम: सुरक्षा, भय निवारण, बाधा मुक्ति। 40 दिनों (एक <em>मंडल</em>) की नियमित साधना से ध्यान देने योग्य प्रभाव होते हैं।',
    mantra_batuk_sub: 'बटुक = भैरव का शाश्वत युवा रूप — सभी भक्तों के लिए सबसे सुलभ',
    mantra_batuk_desc: 'यह सबसे लोकप्रिय और सुलभ भैरव मंत्रों में से एक है। न्यूनतम 108 बार जप करें। अचानक आने वाले खतरों, स्वास्थ्य संकटों, यात्रा सुरक्षा और अचानक भाग्य परिवर्तन को दूर करने में अत्यंत प्रभावी। स्रोत: <em>बटुक भैरव तंत्रम</em>।',
    mantra_beej_sub: 'बीज मंत्र केंद्रित कंपन बीज हैं — शक्तिशाली और प्रत्यक्ष। उन्नत साधकों के लिए।',
    mantra_beej1_title: 'भैरव बीज',
    mantra_beej1_text: '<em>हृीं</em> — भैरव का प्राथमिक बीज। उनकी शक्ति, माया-भेदन ऊर्जा और ब्रह्मांडीय चेतना से सीधे संबंध का प्रतिनिधित्व करता है। तंत्र में मूल बीज अक्षर के रूप में प्रयुक्त।',
    mantra_beej2_title: 'काल बीज',
    mantra_beej2_text: '<em>क्रीं</em> — काली का बीज, कालशक्ति। काल भैरव साधना में काल-अतिक्रमण और कर्म के विघटन के पहलू को आह्वान करने के लिए प्रयुक्त।',
    mantra_beej3_title: 'मृत्यु बीज',
    mantra_beej3_text: '<em>ॐ</em> — सार्वभौमिक ध्वनि, सभी मंत्रों का बीज। ब्रह्मांडीय अनुनाद स्थापित करने के लिए सदा भैरव मंत्रों से पहले आता है।',
    mantra_ashtakam_sub: 'आदि शंकराचार्य द्वारा 8 श्लोकों का यह स्तोत्र — काल भैरव पर सबसे पूर्ण भक्ति ग्रंथ',
    mantra_ashtakam_desc: 'अष्टकम काल भैरव की महिमा, गुणों और कृपा का वर्णन करने वाला 8 पदों का प्राचीन संस्कृत पाठ है। नीचे प्रत्येक श्लोक का विवरण उसके अर्थ और महत्व सहित दिया गया है। पूर्ण संस्कृत पाठ <em>शंकराचार्य स्तोत्र संग्रह</em> में मिलता है।',
    mantra_tantric_warn_title: '⚠ तांत्रिक साधनाओं पर महत्वपूर्ण चेतावनी',
    mantra_tantric_warn_text: 'निम्नलिखित जानकारी केवल <strong>शैक्षणिक उद्देश्यों के लिए</strong> दी गई है। यहाँ वर्णित तांत्रिक साधनाएं <strong>केवल</strong> उन व्यक्तियों द्वारा की जानी चाहिए जिन्होंने योग्य शैव या तांत्रिक गुरु से दीक्षा प्राप्त की हो। उचित दीक्षा, तैयारी या मार्गदर्शन के बिना तांत्रिक अनुष्ठान करने के विपरीत प्रभाव हो सकते हैं। <strong>सभी साधनाएं विशेष रूप से व्यक्तिगत आध्यात्मिक लाभ के लिए हैं — दूसरों को हानि पहुंचाने के लिए कभी नहीं।</strong> यह वेबसाइट और इसके निर्माता किसी भी परिणाम के लिए उत्तरदायी नहीं हैं।',
    mantra_tantric1_title: 'श्मशान साधना',
    mantra_tantric1_text: 'मध्यरात्रि में श्मशान भूमि में की जाने वाली उन्नत साधना। उचित दीक्षा, निर्भयता और मार्गदर्शन की आवश्यकता है। भैरव की उपस्थिति का अनुभव करने का सबसे प्रत्यक्ष तरीका माना जाता है। केवल दीक्षित तांत्रिकों के लिए।',
    mantra_tantric2_title: 'भैरव यंत्र',
    mantra_tantric2_text: 'भैरव के ब्रह्मांडीय रूप का प्रतिनिधित्व करने वाला ज्यामितीय आरेख (यंत्र)। मंत्र और अनुष्ठान द्वारा ऊर्जान्वित किया जाता है और पूजा स्थान में रखा जाता है। सुरक्षा और आशीर्वाद के लिए भैरव ऊर्जा का स्थायी केंद्र बिंदु बनता है।',
    mantra_tantric3_title: 'पुरश्चरण',
    mantra_tantric3_text: 'भैरव के मंत्र की समर्पित पुनरावृत्ति — मूल सक्रियण के लिए न्यूनतम 1,00,000 बार (1 लाख), सामान्यतः 40 दिनों में। पूरी अवधि के दौरान विशिष्ट आहार, व्यवहार और अनुष्ठान प्रतिबंधों का पालन आवश्यक है।',
    mantra_tantric4_title: 'अमावस्या साधना',
    mantra_tantric4_text: 'अमावस्या की रात्रि में की जाने वाली विशेष साधना। मध्यरात्रि से प्रारंभ होती है। मंत्र जप, दीप अर्पण और तिल व लोहे के चढ़ावे शामिल हैं। जिद्दी बाधाओं को दूर करने के लिए अत्यंत प्रभावशाली मानी जाती है।',
    mantra_final_title: 'धर्मपूर्ण साधना का मूल सिद्धांत',
    mantra_final_text: 'सभी प्रामाणिक शैव तांत्रिक परंपराएं सहमत हैं: <strong>भैरव स्वयं उन लोगों को दंडित करते हैं जो उनकी ऊर्जा का दुरुपयोग करते हैं।</strong> वे ब्रह्मांडीय न्याय के कोतवाल हैं। किसी भी साधना का उपयोग दूसरों के हेरफेर, नियंत्रण या हानि के लिए करने पर भैरव का प्रकोप — उनकी कृपा नहीं — प्राप्त होगी। अहंकार, लालच या दुर्भावना से भैरव के पास जाने वाले साधक अपने कर्म को त्वरित और प्रवर्धित पाएंगे। <em>सच्ची भैरव साधना अहंकार को विघटित करती है — उसे फुलाती नहीं।</em>',

    // SEVA PAGE
    seva_header: 'सेवा और दान',
    seva_page_sub: 'कुत्ता भैरव का प्रिय वाहन है — उनके वाहन की सेवा स्वयं भगवान की सेवा है',
    seva_why_title: 'पवित्र कुत्ता — कुत्ता सेवा क्यों है भैरव सेवा',
    seva_how_title: 'कुत्ता सेवा कैसे करें',
    seva_days_title: 'कुत्ता सेवा के सबसे शुभ दिन',
    seva_donate_title: 'कुत्ता सेवा में योगदान करें',
    seva_temple_title: 'मंदिर सेवा — काल भैरव मंदिर, वाराणसी',
    seva_why_src: 'स्रोत: काशी खंड, स्कंद पुराण; काशी के पुजारियों की मौखिक परंपरा',
    seva_why_p1: '<strong class="text-gold">कुत्ता (श्वान)</strong> काल भैरव का केवल वाहन नहीं है — यह उनके स्वभाव का अभिन्न प्रतीक है। कुत्ता इनका प्रतिनिधित्व करता है:',
    seva_why_li1: '<strong class="text-gold">परम निष्ठा</strong> — कुत्ता अपने स्वामी का सभी परिस्थितियों में अनुसरण करता है, जो भैरव के प्रति भक्त की अटूट भक्ति का प्रतीक है',
    seva_why_li2: '<strong class="text-gold">सतर्कता और जागरूकता</strong> — कोतवाल के रूप में भैरव सदा सावधान रहते हैं; कुत्ता कभी ड्यूटी पर नहीं सोता',
    seva_why_li3: '<strong class="text-gold">परदे से परे की अनुभूति</strong> — कहा जाता है कि कुत्ते आत्माओं को देख सकते हैं और जो मनुष्य नहीं देख सकते उसे अनुभव कर सकते हैं; भैरव अपने कुत्ते के साथ श्मशान में विचरण करते हैं',
    seva_why_li4: '<strong class="text-gold">बहिष्कृत और दिव्य</strong> — जाति समाज में कुत्ते को "अशुद्ध" जानवर माना जाता था, फिर भी भैरव — जो स्वयं एक बहिष्कृत कापालिक के रूप में जीते थे — ने कुत्ते को अपना साथी चुना, यह पुष्टि करते हुए कि दिव्यता मानवीय पूर्वाग्रहों से परे है',
    seva_why_quote: 'अनेक ग्रंथ पुष्टि करते हैं: <em>"जो नहीं करवा सकता काशी यात्रा, वो कर ले श्वान सेवा" — "जो काशी की तीर्थ यात्रा नहीं कर सकता वह कुत्तों की सेवा करके समान पुण्य प्राप्त कर सकता है।"</em> यह काशी की प्राचीन परंपरा है।',
    seva_card1_title: 'प्रतिदिन भोजन',
    seva_card1_text: 'सेवा का सबसे सरल और सबसे शक्तिशाली रूप। प्रतिदिन एक आवारा कुत्ते को खिलाएं — विशेषकर रविवार, मंगलवार या भैरव अष्टमी को। पका हुआ भोजन, रोटी या अच्छा कुत्ते का खाना दें। काला कुत्ता सबसे शुभ है।',
    seva_card2_title: 'पशु चिकित्सा देखभाल',
    seva_card2_text: 'किसी घायल या बीमार आवारा कुत्ते का इलाज करना — पशु चिकित्सक की व्यवस्था करना, घावों पर पट्टी बाँधना या कुत्ते के उपचार में योगदान देना — भैरव पूजा का सबसे प्रत्यक्ष रूप माना जाता है।',
    seva_card3_title: 'आश्रय सहयोग',
    seva_card3_text: 'कुत्तों के आश्रयों और बचाव संगठनों को आर्थिक रूप से या अपने समय से सहयोग करना सेवा का एक गहन कार्य है। भैरव सभी सड़क के कुत्तों की देखभाल करते हैं — आपकी सेवा सीधे उन तक पहुँचती है।',
    seva_card4_title: 'गर्मी में पानी',
    seva_card4_text: 'अपने घर के बाहर सड़क के कुत्तों और पक्षियों के लिए साफ पानी के कटोरे रखें, विशेषकर गर्म महीनों में। भैरव परंपरा में यह सरल कार्य अत्यंत पुण्यकारी माना जाता है।',
    seva_card5_title: 'नसबंदी कार्यक्रम',
    seva_card5_text: 'ABC (पशु जन्म नियंत्रण) कार्यक्रमों का समर्थन करना जो मानवीय रूप से आवारा कुत्तों की नसबंदी करते हैं, कष्ट को कम करता है। ऐसे कार्यक्रमों में योगदान एक दयालु और धर्मपूर्ण कार्य है।',
    seva_card6_title: 'सरल करुणा',
    seva_card6_text: 'किसी कुत्ते को स्वीकार करना, प्यार से पुचकारना या धीरे से बोलना भी सेवा का एक कार्य है। भैरव हर कुत्ते की आँखों में उपस्थित हैं।',
    seva_table_th1: 'दिन / अवसर', seva_table_th2: 'महत्व', seva_table_th3: 'अनुशंसित सेवा',
    seva_row1_day: 'काल भैरव अष्टमी', seva_row1_sig: 'भैरव का सबसे पवित्र वार्षिक दिन', seva_row1_seva: '8 या अधिक कुत्तों को खिलाएं; कुत्ते के आश्रय को दान करें',
    seva_row2_day: 'हर रविवार', seva_row2_sig: 'भैरव का साप्ताहिक दिन', seva_row2_seva: 'अपना खाना खाने से पहले कम से कम एक कुत्ते को खिलाएं',
    seva_row3_day: 'अष्टमी तिथि (मासिक)', seva_row3_sig: '8वाँ चंद्र दिन — भैरव को पवित्र', seva_row3_seva: 'कुत्तों को खिलाएं और उनकी देखभाल में योगदान करें',
    seva_row4_day: 'अमावस्या (नई चंद्रमा)', seva_row4_sig: 'भैरव की शक्ति की रात', seva_row4_seva: 'रात को कुत्तों के लिए भोजन रखें',
    seva_row5_day: 'दिवाली / नरक चतुर्दशी', seva_row5_sig: 'पितरों और भैरव की रात', seva_row5_seva: 'इस रात कुत्तों को विशेष भोजन दें',
    seva_row6_day: 'शिवरात्रि', seva_row6_sig: 'शिव-भैरव की रात', seva_row6_seva: 'शिव पूजा के साथ कुत्ते को खिलाना जोड़ें',
    seva_donate_heading: 'काल भैरव के नाम पर आवारा कुत्तों के कल्याण में सहयोग करें',
    seva_donate_text: 'आपका दान आवारा कुत्तों — भगवान काल भैरव के जीवित वाहनों — को खिलाने, उनका इलाज करने और उन्हें आश्रय देने में योगदान देता है। हर योगदान, चाहे कितना भी छोटा हो, भक्ति का प्रत्यक्ष कार्य है और काशी के भगवान का आशीर्वाद दिलाता है।',
    seva_donate_select: 'राशि चुनें (₹)',
    seva_donate_contact_note: 'दान UPI / बैंक ट्रांसफर के माध्यम से किया जा सकता है। विवरण के लिए seva@kaalbhairav.org पर संपर्क करें।',
    seva_donate_btn: 'दान विवरण के लिए संपर्क करें',
    seva_donate_amounts: '₹51 से 3-5 कुत्तों को एक दिन का भोजन मिलता है &nbsp;|&nbsp; ₹108 से आपातकालीन पशु चिकित्सा &nbsp;|&nbsp; ₹1008 से एक कुत्ते की मासिक देखभाल',
    seva_temple_p1: 'वाराणसी में <strong class="text-gold">काल भैरव मंदिर</strong> (काल भैरव गली, त्रिलोचन के पास) भारत का सबसे महत्वपूर्ण भैरव मंदिर है। कहा जाता है कि काशी में स्थायी रूप से बसने से पहले पहले काल भैरव की अनुमति लेनी होती है — और भक्त काशी विश्वनाथ से पहले इस मंदिर में जाते हैं।',
    seva_temple_p2: 'इस मंदिर में सेवा में शामिल हैं: अन्न-दान, दीप-दान, अभिषेक सेवा, और मंदिर परिसर में कुत्तों को खिलाना। यदि आप व्यक्तिगत रूप से नहीं आ सकते तो मंदिर के पुजारी आपकी ओर से विशेष सेवाएं करवा सकते हैं।',
    seva_temple_p3: '<strong class="text-gold">मंदिर का पता:</strong><br>काल भैरव मंदिर, काल भैरव गली,<br>त्रिलोचन के पास, वाराणसी (काशी), UP — 221001',
    seva_shrines_title: 'अन्य महत्वपूर्ण भैरव मंदिर',

    // DISCLAIMER PAGE
    disc_header: 'अस्वीकरण और उपयोग की शर्तें',
    disc_sub: 'इस वेबसाइट पर वर्णित किसी भी आध्यात्मिक साधना को करने से पहले कृपया ध्यान से पढ़ें',

    // NAV
    nav_home: 'होम',
    nav_about: 'परिचय',
    nav_stories: 'कथाएं',
    nav_64: '64 भैरव',
    nav_kashi: 'काशी',
    nav_pooja: 'पूजा विधि',
    nav_mantra: 'मंत्र और तंत्र',
    nav_seva: 'कुत्ता सेवा',
    nav_disclaimer: 'अस्वीकरण',

    // FOOTER
    footer_tagline: 'जय काल भैरव · Jay Kaal Bhairav · कुत्ता काल भैरव का पवित्र वाहन है। पशुओं पर दयालु रहें।',
    footer_copy: '&copy; ' + new Date().getFullYear() + ' KaalBhairav.org · सर्वाधिकार सुरक्षित',

    // INDEX — HERO
    hero_title: 'काल भैरव',
    hero_subtitle: 'काशी के कोतवाल · काल के स्वामी · अहंकार के नाशक',
    hero_desc: 'जो ब्रह्मा की खोपड़ी धारण करते हैं। जो श्मशान घाट पर विचरण करते हैं। जो स्वयं काल हैं — वाराणसी के उग्र, करुणामय संरक्षक, वह शाश्वत नगरी जहाँ मृत्यु मोक्ष है।',
    btn_pooja: 'पूजा विधि',
    btn_mantra: 'मंत्र और तंत्र',
    btn_stories: 'पवित्र कथाएं',

    // INDEX — WHO IS
    who_title: 'काल भैरव कौन हैं?',
    who_p1: '<strong class="text-gold">काल भैरव</strong> भगवान शिव का सबसे उग्र और शक्तिशाली रूप है। नाम में <em>काल</em> (समय/मृत्यु) और <em>भैरव</em> (भयंकर, भयावह) का संयोजन है। वे वह देव हैं जो स्वयं काल से परे हैं — और साथ ही काल स्वरूप भी हैं।',
    who_p2: 'उन्हें एक काले, नग्न देवता के रूप में दर्शाया जाता है जो खोपड़ियों की माला धारण करते हैं, हाथों में कपाल, त्रिशूल, डमरू और पाश लिए हुए हैं। उनका वाहन (<em>वाहन</em>) एक काला कुत्ता है — एक पवित्र पशु जो वफ़ादारी, सतर्कता और मानव की अदृश्य शक्ति का प्रतीक है।',
    who_p3: '<strong class="text-gold">वाराणसी (काशी)</strong> में उन्हें <em>कोतवाल</em> के रूप में पूजा जाता है — दिव्य पुलिस आयुक्त — जो भगवान शिव की ओर से इस शाश्वत नगरी का शासन करते हैं। काशी में बिना उनकी अनुमति के कोई न प्रवेश कर सकता है न निकल सकता है।',
    attr_title: 'प्रमुख विशेषताएं',
    attr_h1: 'विशेषता', attr_h2: 'विवरण',
    attr_name: 'अन्य नाम', attr_name_val: 'क्षेत्रपाल, कोतवाल, दंडपाणि',
    attr_form: 'रूप', attr_form_val: 'शिव का उग्र रूप',
    attr_vahana: 'वाहन', attr_vahana_val: 'काला कुत्ता (श्वान)',
    attr_color: 'रंग', attr_color_val: 'गहरा नीला / काला',
    attr_day: 'विशेष दिन', attr_day_val: 'भैरव अष्टमी, रविवार, मंगलवार',
    attr_dhaam: 'प्रमुख धाम', attr_dhaam_val: 'काल भैरव मंदिर, वाराणसी',
    attr_river: 'पवित्र नदी', attr_river_val: 'शिप्रा (उज्जैन), गंगा (काशी)',
    attr_forms: 'रूप', attr_forms_val: '64 भैरव (अष्टभैरव × 8)',

    // INDEX — CARDS
    cards_title: 'पवित्र ज्ञान की खोज करें',
    card1_title: 'पवित्र कथाएं',
    card1_text: 'ब्रह्मा का शिरच्छेदन, काल भैरव की उत्पत्ति, काशी कोतवाल की कथा, और शिव पुराण, स्कंद पुराण एवं तांत्रिक ग्रंथों की कहानियां।',
    card2_title: 'भैरव के 64 रूप',
    card2_text: '64 भैरव — 8 अष्टभैरव, प्रत्येक के 8 उप-रूप। प्रत्येक रूप एक विशिष्ट दिशा, शक्ति और ब्रह्मांडीय ऊर्जा का पहलू संचालित करता है।',
    card3_title: 'पूजा विधि',
    card3_text: 'काल भैरव पूजा की पूर्ण चरण-दर-चरण विधि — आवश्यक सामग्री, संकल्प, अभिषेक, नैवेद्य, आरती और आध्यात्मिक प्रभाव।',
    card4_title: 'मंत्र और तंत्र',
    card4_text: 'मूल मंत्र, अष्टकम, भैरव गायत्री, बीज मंत्र और तांत्रिक साधनाएं — उचित मार्गदर्शन, प्रभाव और उचित उपयोग सिद्धांतों के साथ।',
    card5_title: 'कुत्ता सेवा और दान',
    card5_text: 'कुत्ता भैरव का पवित्र वाहन है। कुत्तों को खिलाना और उनकी देखभाल करना — विशेषकर आवारा कुत्तों की — भैरव सेवा का सर्वोच्च रूप है।',
    card6_title: 'काल भैरव का परिचय',
    card6_text: 'प्रतिमा विज्ञान, महत्व, शैवाद और तंत्र से संबंध, विभिन्न परंपराओं में भैरव — शैव, शाक्त और नाथ संप्रदाय।',

    // INDEX — MANTRA
    mantra_title: 'मूल मंत्र',
    mantra_meaning: '"ॐ हृीं बटुकाय आपदुद्धारणाय कुरु कुरु बटुकाय हृीं"<br><em>हे बटुक भैरव, कृपया मेरे जीवन से सभी बाधाएं और कष्ट दूर करें।</em>',
    mantra_guide: 'प्रतिदिन 108 बार जप करें, अधिमानतः रविवार या मंगलवार को, दक्षिण दिशा में मुख करके।',
    btn_copy: 'मंत्र कॉपी करें',

    // INDEX — KASHI
    kashi_title: 'काशी — शाश्वत नगरी',
    kashi_source: 'स्रोत: काशी खंड, स्कंद पुराण',
    kashi_story_title: 'काल भैरव काशी के संरक्षक क्यों हैं',
    kashi_p1: 'जब भगवान शिव ने काशी को अपना स्थायी निवास बनाने का निर्णय किया, तो उन्हें नगरी के लिए एक शाश्वत संरक्षक की आवश्यकता थी — जो ब्रह्मांडीय व्यवस्था बनाए रखे, अपराधियों को दंडित करे और नगर की सीमाओं के भीतर मरने वाली प्रत्येक आत्मा को मोक्ष प्रदान करे।',
    kashi_p2: 'उन्होंने <strong class="text-gold">काल भैरव</strong> को <em>कोतवाल</em> — काशी के रक्षक — के रूप में नियुक्त किया। वाराणसी की काल भैरव गली में काल भैरव मंदिर नगरी के सबसे महत्वपूर्ण मंदिरों में से एक है, और कहा जाता है कि काशी विश्वनाथ के दर्शन से पहले काल भैरव के दर्शन आवश्यक हैं — शाश्वत नगरी में प्रवेश की अनुमति लेने के लिए।',
    kashi_p3: 'परंपरा के अनुसार, काशी की सीमाओं के भीतर स्वयं यमराज (मृत्यु के देव) का भी कोई अधिकार नहीं है — यहाँ मृत्यु और मोक्ष पर केवल काल भैरव का अधिकार है। काशी से जाने वाली प्रत्येक आत्मा को काल भैरव की कृपा से स्वयं भगवान शिव द्वारा कान में <em>तारक मंत्र</em> सुनाया जाता है।',
    btn_all_stories: 'सभी पवित्र कथाएं पढ़ें →',

    // INDEX — DOG SEVA
    seva_title: 'कुत्ते को खिलाएं, भैरव को प्रसन्न करें',
    seva_desc: 'काला कुत्ता काल भैरव का <em>वाहन</em> और सबसे प्रिय पशु है। आवारा कुत्ते को खिलाना — विशेषकर रविवार, भैरव अष्टमी या काल भैरव जयंती पर — भक्ति का सबसे शक्तिशाली कार्य माना जाता है।',
    btn_seva: 'कुत्ता सेवा में योगदान करें',

    // INDEX — DISCLAIMER
    disclaimer_title: '⚠ महत्वपूर्ण सूचना — कृपया पढ़ें',
    disclaimer_text: 'इस वेबसाइट पर वर्णित सभी आध्यात्मिक साधनाएं, मंत्र और तांत्रिक विधियां <strong>केवल शैक्षिक और भक्ति उद्देश्यों के लिए</strong> प्रस्तुत की गई हैं। ये विशेष रूप से <strong>व्यक्तिगत आध्यात्मिक विकास, सुरक्षा और सकारात्मक उद्देश्यों के लिए</strong> हैं। किसी को भी हानि पहुंचाने के लिए किसी भी साधना का उपयोग सख्त वर्जित है। कोई भी साधना पूर्णतः साधक की अपनी जिम्मेदारी पर है।',
    disclaimer_link: 'पूर्ण अस्वीकरण पढ़ें →',
  }
};

// ─── LANGUAGE TOGGLE LOGIC ───
function setLang(lang) {
  localStorage.setItem('kb_lang', lang);
  document.documentElement.setAttribute('lang', lang === 'hi' ? 'hi' : 'en');
  document.querySelectorAll('[data-key]').forEach(el => {
    const key = el.dataset.key;
    if (translations[lang] && translations[lang][key] !== undefined) {
      el.innerHTML = translations[lang][key];
    }
  });
  // Update toggle button label
  const btn = document.getElementById('lang-toggle');
  if (btn) btn.textContent = lang === 'hi' ? 'English' : 'हिंदी';
}

function initLang() {
  const saved = localStorage.getItem('kb_lang') || 'en';
  setLang(saved);
}

document.addEventListener('DOMContentLoaded', initLang);
